PI_IP        = "192.168.2.2"
LAPTOP_IP    = "192.168.2.1"
PI_USERNAME  = "pi"
PI_PASSWORD  = "raspberry"

MAV_PORT       = 14551
VIDEO_PORT     = 5000
SENSOR_PORT    = 14553
MOTOR_CMD_PORT = 14554

FRAME_WIDTH   = 640
FRAME_HEIGHT  = 480
JPEG_QUALITY  = 50
TARGET_FPS    = 25
SOURCE_SYSTEM = 255

MAX_SPEED_SURFACE    = 700
MAX_SPEED_UNDERWATER = 500
MAX_SPEED_BENCH      = 100
THRUSTER_COUNT       = 4
THRUSTER_LABELS      = ["T1", "T2", "T3", "T4"]
THRUSTER_ROLES       = ["FWD-L", "FWD-R", "VRT-L", "VRT-R"]

YOLO_MODEL      = "yolov8n.pt"
YOLO_CONFIDENCE = 0.45
YOLO_ENABLED    = True

GUI_POLL_MS      = 16
LOG_QUEUE_MAXLEN = 500

GAMEPAD_ENABLED          = True
GAMEPAD_POLL_MS          = 50
GAMEPAD_DEADZONE         = 0.12
GAMEPAD_TRIGGER_DEADZONE = 0.05

GAMEPAD_AXIS_LEFT_X  = 0
GAMEPAD_AXIS_LEFT_Y  = 1
GAMEPAD_AXIS_RIGHT_X = 3
GAMEPAD_AXIS_RIGHT_Y = 4
GAMEPAD_AXIS_LT      = 2
GAMEPAD_AXIS_RT      = 5

GAMEPAD_BTN_A     = 0
GAMEPAD_BTN_B     = 1
GAMEPAD_BTN_X     = 2
GAMEPAD_BTN_Y     = 3
GAMEPAD_BTN_LB    = 4
GAMEPAD_BTN_RB    = 5
GAMEPAD_BTN_BACK  = 6
GAMEPAD_BTN_START = 7
GAMEPAD_BTN_L3    = 8
GAMEPAD_BTN_R3    = 9
GAMEPAD_HAT_INDEX = 0

GAMEPAD_SPEED_PROFILES = ["bench", "crawl", "pool", "underwater", "surface"]

MOTOR_CMD_NAMES = {
    "mot_a":   {"on": "MOT_A_ON",   "off": "MOT_A_OFF"},
    "mot_b":   {"on": "MOT_B_ON",   "off": "MOT_B_OFF"},
    "mot_all": {"on": "MOT_ALL_ON", "off": "MOT_ALL_OFF"},
}
MOTOR_ON_VALUE    = 1.0
MOTOR_OFF_VALUE   = 0.0
MOTOR_A_KEY       = "1"
MOTOR_B_KEY       = "2"
MOTOR_ALL_OFF_KEY = "3"

SENSOR_NAMES       = {"dst_front", "dst_left", "dst_right", "dst_back"}
MOTOR_STATUS_NAMES = {"mot_a", "mot_b"}

AVOID_FRONT_CRITICAL_CM = 30
AVOID_FRONT_WARNING_CM  = 60
AVOID_SIDE_CRITICAL_CM  = 20

WANDER_FORWARD_SECS = 3.0
WANDER_TURN_SECS    = 1.5
WANDER_REVERSE_SECS = 1.0

WALL_TARGET_CM = 50
WALL_MIN_CM    = 20
WALL_MAX_CM    = 100

CORRIDOR_TARGET_CM    = 50
CORRIDOR_TOLERANCE_CM = 15
CORRIDOR_MAX_YAW      = 0.4

AUTO_DEFAULT_SPEED  = "pool"
AUTO_LOOP_HZ        = 10
AUTO_SENSOR_STALE_S = 2.0
AUTO_SLOWDOWN_SPEED = "crawl"